version: '3.4'

services:
  clientwebapi_consumer:
    image: ${DOCKER_REGISTRY-}clientwebapiconsumer
    build:
      context: .\Client[webapi_consumer]
      dockerfile: Dockerfile

  companystructured.webapi:
    image: ${DOCKER_REGISTRY-}companystructuredwebapi
    build:
      context: .\CompanyStructured.WebAPI
      dockerfile: Dockerfile

  lc1:
    image:  microsoft/mssql-server-windows-express
    environment:
            SA_PASSWORD: "1Secure*Password1"
            ACCEPT_EULA: "Y"
   
