version: '3.4'

services:
  clientwebapi_consumer:
    image: ${DOCKER_REGISTRY-}clientwebapiconsumer
    environment:
      - ClientUrl=http://sampleclient/
    build:
      context: .\Client[webapi_consumer]
      dockerfile: Dockerfile

  companystructured.webapi:
    image: ${DOCKER_REGISTRY-}companystructuredwebapi
    environment:
      - ApiUrl=http://sampleapi/
    build:
      context: .\CompanyStructured.WebAPI
      dockerfile: Dockerfile

